### PR TITLE
Add environment variable for smooth scrolling

### PR DESCRIPTION
**Pull request by onodera-punpun**

### CODE REVIEW

**Comment by vain** [comment]
This has recently been discussed over here:

https://github.com/vain/lariza/issues/36#issuecomment-296364146

I know the code change is minimal, but see my reasoning in the linked issue.

It's a delicate matter. Which customization options should I support? Should I support everything that WebKit has to offer? Then the code base would be very large. Should I support "some" options? Which ones?

Right now, lariza supports only those options that I use myself. Well, even that's a lie, because I don't use the following options anymore: accepted language, user agent, zoom. I *should* remove them, but I've kept them in order to not break things.

I'd love for such customization options to live in people's forks. I understand, though, that this can be annoying and a lot of work for other people. On the other hand, I want to keep lariza's code as minimal as possible to ease *my* maintenance burden.

I think I'll close this PR for now (sorry). I'm not happy with the current customization situation, but I don't see any good alternatives right now.

(It would be awesome (for me) if WebKit had its own environment variables for this or a config file ...)

**Comment by onodera-punpun** [comment]
No problem.

You might want to consider creating a PATCHES.md or something where people can link patches. That way you can keep your codebase clean and lean, but people can pick and choose parches if they prefer. Like how suckless does.

**Comment by vain** [comment]
Yeah, that's a good idea. Will do!

**Comment by vain** [comment]
`PATCHES` has been added and I added your repo as well. If you'd rather not want your repo to show up in that list, just drop me a note. :)

**Pull request closed without merging**
