### PR TITLE
Disable JS with ENV

### PR DESCRIPTION
**Pull request by beli3ver**
Now the user can disable JS.

### CODE REVIEW

**Comment by vain** [comment]
I'm curious, how do you (personally) use that? Do you disable JS globally all the time? Or only for some web sites? How do you turn it on and off? By launching different instances of lariza with different environment variables?

**Comment by beli3ver** [comment]
Yes. I have two entries in my menu (fluxbox) to use it with and without it.
I am not the friend of JS on many sites.

**Comment by vain** [comment]
So, you don't feel the need to turn on JS for a web site *which is currently loaded*?

I'm sceptical about the usefulness of a JS toggle. Of course, it depends a lot on your browsing habits and on which web sites you visit on a regular basis.

I have to admit, though: I just disabled JS, visited a few web sites and was blown away. The performance boost is massive. I really didn't expect/remember that.

I'll keep JS disabled for a few days and check how often I have to re-enable it. Maybe I'll add a hotkey for that after all. And a little indicator showing the current status would be nice. If, however, I end up re-enabling JS all the time, then adding an option to disable it is not a useful feature for me and your fork should probably be added to `PATCHES`. :)

**Comment by beli3ver** [comment]
The performance is the reason I do it. When I am on the route I often have only edge connection, so it is really useful to deactivate JS.
It would eb create to have a hotkey fro this.

Malte
15. Juni 2017 18:50, "vain"  schrieb:
	So, you don't feel the need to turn on JS for a web site which is currently loaded? 

	I'm sceptical about the usefulness of a JS toggle. Of course, it depends a lot on your browsing habits and on which web sites you visit on a regular basis. 

	I have to admit, though: I just disabled JS, visited a few web sites and was blown away. The performance boost is massive. I really didn't expect/remember that. 

	I'll keep JS disabled for a few days and check how often I have to re-enable it. Maybe I'll add a hotkey for that after all. And a little indicator showing the current status would be nice. If, however, I end up re-enabling JS all the time, then adding an option to disable it is not a useful feature for me and your fork should probably be added to PATCHES. :)

**Comment by vain** [comment]
I've been trying to live without JS since I wrote that comment above. Sadly, I needed to re-enable it for a lot of pages. I didn't keep count, but it was often enough to be annoying. :( I can't even preview this comment right here without JS.

As I said earlier, you're invited to add your fork to [`PATCHES`](https://github.com/vain/lariza/blob/master/PATCHES). (There's a minor typo, though, in line 606 it should say `disabled_javascript = ...`.)

There's a couple of things that could be useful for users with "slow" internet access. For example, one might think of disabling images or plugins as well, or maybe even disable DNS prefetching. All of that should exist in the form of forks/patch sets.

**Pull request closed without merging**
